### ISSUE TITLE
Don't warn when base packages are missing from DESCRIPTION

### ISSUE THREAD

**Issue by DanChaltiel** [DanChaltiel/autoimport#31]
```
Messages d'avis :
1: Importing functions not listed in the Imports section of DESCRIPTION:
→ `stats::na.omit()` in ./R/ae_table_soc.R
→ `stats::rbinom()` in ./R/ae_table_soc.R
```

**Comment by mihem** [comment]
But isn't this a good thing?
In Wickhams book "R packages" it says

> If you plan to submit a package to CRAN, note that this even applies to functions in packages that you think of as “always available”, such as [stats::median()](https://rdrr.io/r/stats/median.html) or [utils::head()](https://rdrr.io/r/utils/head.html).

Source: https://r-pkgs.org/whole-game.html#use_package

So Ithink a warning here is a good thing. People who don't want to submit to CRAN can just ignore it.

**Comment by DanChaltiel** [comment]
I don't know where that came from, I was certain I saw a post saying "you should not Import base packages in your DESCRIPTION file as they are packed with R", but I obviously cannot find it back.
Or maybe it was a ChatGPT answer that I gullibly believed.
Or maybe I'm starting to dream about R packages.

Thanks a lot for the notice 😄
