### ISSUE TITLE
autoimport() is missing some extraction of explicit function in the code

### ISSUE THREAD

**Issue by cregouby** [DanChaltiel/autoimport#4]
**Current situation**
Being very inspired by the presentation at RR_2023 Avignon, I've run autoimport() on the code in https://github.com/mlverse/tabnet
I'm impressed by the user interface but the parsing is missing some explicit <package>::<function>() statements in the code : 

missing @ImportFrom have been manually added in a specific commit and can be seen in few locations like : 
- https://github.com/mlverse/tabnet/commit/3ec6b0716e5ea50660ebb8cf92910c26cee0d05b#diff-4e36c4149b4e2837f4fef39996041c6f5e75ecade215313b3fa35bea595ba162R398
- https://github.com/mlverse/tabnet/commit/3ec6b0716e5ea50660ebb8cf92910c26cee0d05b#diff-1e36bd726e25b876564d0c896324fc80c919576e022f550168f4fbd57c265249R35
- https://github.com/mlverse/tabnet/commit/3ec6b0716e5ea50660ebb8cf92910c26cee0d05b#diff-1e36bd726e25b876564d0c896324fc80c919576e022f550168f4fbd57c265249R489
- https://github.com/mlverse/tabnet/commit/3ec6b0716e5ea50660ebb8cf92910c26cee0d05b#diff-1e36bd726e25b876564d0c896324fc80c919576e022f550168f4fbd57c265249R566

**Reproducible example**
```r
# git clone https://github.com/mlverse/tabnet
# cd tabnet
library(autoimport)
autoimport(files = "R/tab-network.R")
```

**Comment by DanChaltiel** [comment]
I think this is corrected in 6dd0769.
Please reopen if not.
