### ISSUE TITLE
`autoimport()` unexpectidly removes some required `#' @importFrom `

### ISSUE THREAD

**Issue by cregouby** [DanChaltiel/autoimport#5]
# Current situation
 I've run `autoimport()` on the code in https://github.com/mlverse/tabnet
and I get some unexpected removal of existing and required  Roxygen `#' @importFrom`

## Before `autoimport()` 
- file `R/plot.R`  includes the following lines where importFrom in line 20 is used in  line 45 of code:
https://github.com/mlverse/tabnet/blob/7186ba6048a6818283d05fb86c2af6ead862173b/R/plot.R#L20-L45

- file `R/parsnip.R`  includes the following lines where importFrom in  line 302 is used in  line 303 of the code:
https://github.com/mlverse/tabnet/blob/7186ba6048a6818283d05fb86c2af6ead862173b/R/parsnip.R#L300-L307

## After `autoimport()`
- file `R/plot.R`  is missing the `#' @importFrom rlang .data` 
![image](https://github.com/DanChaltiel/autoimport/assets/10136115/4caae3c7-c567-4aeb-aef5-1fa2520102cb)

- file `R/parsnip.R` is missing the `#' @importFrom stats update`
![image](https://github.com/DanChaltiel/autoimport/assets/10136115/3d88f5c8-7d77-4e08-a7b6-98054133eb4a)

**Reproducible example**

``` r
# git clone https://github.com/mlverse/tabnet
# cd tabnet
library(autoimport)
library(tidyverse)
autoimport(files = "R/plot.R")
autoimport(files = "R/parsnip.R")

```

**Comment by DanChaltiel** [comment]
Missing `rlang::.data` is expected as it is never called as a function. 

Likely, `stats::update()` is not really used on line 303 of your file. You are extending a method and so you might need to import the generic, but you aren't calling the generic per see. 

As for pipes, you should import these from the package description (`usethis::use_package_doc()`). 

This is a known limitation of `autoimport` as it uses `utils::getSrcref()`. I have no idea how to overcome this limitation 😞.

This is described [in the readme](https://github.com/DanChaltiel/autoimport#false-negatives) but I should add these specific cases.

**Comment by cregouby** [comment]
Thanks a lot for this advanced analysis and the hints 🙏🏽  and sorry that I read the README too quickly  😞

**Comment by DanChaltiel** [comment]
Hi Cedric!
After a very long time, I took some time to update autoimport :-)
Has `usethis::use_package_doc()` fixed your problem?
Also, I've made some significant updates lately. Would you mind trying it again and telling me if any unexpected behaviour happens?

**Comment by DanChaltiel** [comment]
I'm closing the issue, but don't hesitate to reopen if needed.
