### ISSUE TITLE
`autoimport()` tries to include R6 public methods as `@importFrom`

### ISSUE THREAD

**Issue by cregouby** [DanChaltiel/autoimport#6]
# Current situation
 I've run `autoimport()` on the code in https://github.com/mlverse/tabnet
and I get some unexpected insertion of R6 public methods as  Roxygen `#' @importFrom`

## Before `autoimport()` 
- the following code chunk uses `view` and `transpose` as public methods of the torch R6 object `rho` 
https://github.com/mlverse/tabnet/blob/7186ba6048a6818283d05fb86c2af6ead862173b/R/sparsemax.R#L2-L10

- idem for `gather` 
https://github.com/mlverse/tabnet/blob/7186ba6048a6818283d05fb86c2af6ead862173b/R/sparsemax.R#L19

- idem for  `clone` and `squeeze` 
https://github.com/mlverse/tabnet/blob/7186ba6048a6818283d05fb86c2af6ead862173b/R/sparsemax.R#L41-L44

## After `autoimport()`
-` autoimport()` add erroneously import from functions from exotic libraries, messing up the `NAMESPACE` file and `DESCRIPTION` file
![image](https://github.com/DanChaltiel/autoimport/assets/10136115/f184a2c8-5145-4522-a587-0f51d4d98e4e)

**Reproducible example**

``` r
# git clone https://github.com/mlverse/tabnet
# cd tabnet
library(autoimport)
library(tidyverse)
autoimport(files = "R/sparsemax.R")

```

**Comment by DanChaltiel** [comment]
Yes, this is also a known limitation from `utils::getSrcref()`.
As soon as something is recognized as a function it calls an `@importFrom`.
I don't know how I could make a special case for R6 as this is not an inbuilt feature of R. I'm not even sure this is possible.
Of course, I'd gladly accept a PR if you manage to find a solution.

BTW, thank you for your very nice and readable issues 👍

**Comment by cregouby** [comment]
Thanks !
